version: '3.8'

services:
  stock-dashboard:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development services (uncomment for development)
  # frontend-dev:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   depends_on:
  #     - stock-dashboard

  # backend-dev:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "8001:8000"
  #   volumes:
  #     - ./backend:/app
  #   environment:
  #     - PYTHONPATH=/app
  #     - PYTHONUNBUFFERED=1
  #   command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

networks:
  default:
    name: stock-dashboard-network
